### ISSUE TITLE
Support exFAT format on source/destination keys

### ISSUE THREAD

**Issue by Rafiot** [CIRCL/Circlean#15]
I'm not sure pmount can do that, need to check that out.

**Comment by dputtick** [comment]
I did more research into this and tested - the current version of pmount cannot handle exFAT keys for read-only or read-write. It looks like there have been patches for exFAT support via fuse (similar to how pmount supports NTFS) but they haven't been merged. There might be a way to use mount without root permissions for exFAT keys, but that's probably not a road we want to go down at the moment considering 99% of USB keys in the wild are FAT formatted.

**Comment by lupiter** [comment]
In 2019 I'm seeing a lot of exFAT devices and it seems like [pmount is not maintained?](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=755434) Would it be possible to switch to or add support for FUSE? [exfact-fuse](https://packages.debian.org/sid/exfat-fuse) and [exfact-utils](https://packages.debian.org/stretch/exfat-utils) seems to be the usual way at the moment.

**Comment by Rafiot** [comment]
Very, very probably, yes. 

I'll try to work on it as soon as possible, but if you have the chance to give it a go, a PR is more than welcome :)

**Comment by Rafiot** [comment]
That should fix it: https://github.com/CIRCL/Circlean/commit/6f5d09d374f249caac2c83830932ad32dcf416a7

I'll publish a new version of the image this week.

**Comment by Rafiot** [comment]
And if you want to give it a try, here is the new image https://www.circl.lu/assets/CIRCLean/2020-01-16_CIRCLean.img.gz - 6d72aab7eb5e04b73409bf36aac7a52093d4865456e894b2d8fb07c41cac1157

**Comment by lupiter** [comment]
So fast! Thanks very much, I'll try it out soon.
