### ISSUE TITLE
LED not lighting up

### ISSUE THREAD

**Issue by Beercow** [CIRCL/Circlean#16]
Circlean 1.2 the music plays but the LED is not lighting up. LED lights up if connecting from 3.3v pin to ground so there does not seem to be an issue with the LED. GPIO 4 to ground does not work.

**Comment by Rafiot** [comment]
I did not try the LED for a long time, but if you tell me that the GPIO 4 is not working on your rPi, are you sure it is not an hardware problem on your device?

**Comment by Beercow** [comment]
I'll do some testing with some previous versions of Circlean to see if it lights up. I do not believe it is hardware related.

**Comment by Rafiot** [comment]
Woops, sorry about that, it seems I commented the line in the script... 

https://github.com/CIRCL/Circlean/blob/master/fs/etc/rc.local#L31

**Comment by Beercow** [comment]
That was it. Looks like the last commit to the file was when the change was made. Not sure if you want to update the file. I don't see the need to create a pull request for this.

**Comment by Beercow** [comment]
On a side note. If I wanted to change GPIO 4 to another pin, can I just change the pin number in the LED.C file and recompile it?

**Comment by Rafiot** [comment]
Yep, it should just work: https://www.raspberrypi.org/documentation/usage/gpio/
