### ISSUE TITLE
Not working on Raspberry Pi 2

### ISSUE THREAD

**Issue by Rafiot** [CIRCL/Circlean#31]
It seems the conversion silently fails on Rpi2, it is probably related to pdf2htmlex that has been manually compiled on a Rpi1 some times ago.

**Comment by Rafiot** [comment]
Tested on Raspberry Pi 2 V1.1, working.

**Comment by Rafiot** [comment]
#23

**Comment by dputtick** [comment]
Looks like this can be closed since we don't use pdf2html anymore.
