### ISSUE TITLE
Issues with Raspberry Pi 2 Model B

### ISSUE THREAD

**Issue by bubbachubs** [CIRCL/Circlean#36]
Having some major issues with the CIRClean Sanitizer and RP2MB. 

Tried the latest official prebuild release, latest beta release and also the revision here that was quoted as working with RP2:
https://github.com/CIRCL/Circlean/issues/23 

I've only had one successful PDF converted to HTML. .DOC files are not processing at all. .DOCX are being labelled as DANGEROUS but no conversion is taking place. Most times, the music plays for 5 seconds and the destination flash drive has nothing present on the drive (not even logs!).

Any suggestions?

**Comment by dputtick** [comment]
Hey @bubbachubs, let me know if you're still interested in using CIRClean - would like to help debug this is you are
