### ISSUE TITLE
username password

### ISSUE THREAD

**Issue by muehan** [CIRCL/Circlean#38]
I use the pre-build image (last update: 2015-11-06) and a Raspberry Pi 1 Model B.

> all files just gets renamed to "filename.extension.txt" but stay the same.

according the nodes:
- if you want to ssh into the rPi username is 'pi' password 'raspberry' as per defaults
  => is not the case, can not login if I connect a screen and keyboard and use default
  
  and the ip address is 192.168.1.89
  => is not the case, I can not find the raspberry in the network with that IP address

is the documentation not for the prebuild image? Is there another documentation for the image?

thanks

**Comment by dputtick** [comment]
Hey @muehan, would be happy to help debug this if you're still interested in using CIRCLean

**Comment by dputtick** [comment]
Closing this issue, please open a new one if you'd like help debugging!
