### ISSUE TITLE
Some MIDI files seems to not be public domain or a free license

### ISSUE THREAD

**Issue by adulau** [CIRCL/Circlean#4]
Some MIDI files seems to not be public domain or a free license (e.g. The Daft Punk song). To avoid copyright issue while caring or distributing such device, we should reduce the set of MIDI files to freely licensed files (along with the original music being public domain or under a free license).

**Comment by dputtick** [comment]
After discussion with @Rafiot, closing this for now. If this becomes a problem, we can easily add some public domain music instead :).
