### ISSUE TITLE
Prebuild Image Not Working

### ISSUE THREAD

**Issue by LarrySuto1** [CIRCL/Circlean#42]
I have tried the prebuild image on the Raspberry PI 1 and 2....I am not getting any pdfs converted. They are just deleted. Also .doc files are deleted and .docx files are sometime converted to garbage or are just labeled dangerous. Is there something wrong? Should I just build an image from scratch?

**Comment by Bratik** [comment]
Prebuild image not working for me neither, using a Raspberry PI 2

**Comment by Rafiot** [comment]
Are you using this image? 
https://www.circl.lu/assets/CIRCLean/2016-04-26_CIRCLean.img.gz

I tested it on RaspberryPi 1, 2 and 3 

The most recent image isn't supposed to convert the files anymore, only search for active content. it is highly possible you have false positives as the tests on the default image are very strict but I'm happy to look at it so if you can share the docs creating false positive, that would be great.

**Comment by Bratik** [comment]
in my case the image seems to be broken, I tried to write it with dd on my linux laptop several times and I just tried with win32diskImager just to be sure.
Raspbian seems to be booting during a few seconds, showing some informations, warnings and error codes fastly then the raspberry shuts down, no change is made to the usb keys attached.(top left and top right)

**Comment by Rafiot** [comment]
And you DD the image I just mentioned (after you gunzip it), right? Because that's super awkward as it works for me.

**Comment by Bratik** [comment]
Yes that's what I'm doing, i'm gonna try with another micro-SD card when I find one, i'll keep you in touch. The micro-SD card used here is a 8GB Kingston SDHC class 4.

**Comment by LarrySuto1** [comment]
Hi thanks no I was not using that image. I will try. How come the image
does not convert anymore?

**Comment by Rafiot** [comment]
Because it is totally unreliable: relying on libreoffice, poppler and ghostscript on random documents was a bad approach and the raspberry pi was regularly in an unresponsive state with no way for the user to know if it was processing a big file, or stalled. 

I didn't find any sane library to convert the files but if you're aware of one, I'll gladly use it.

**Comment by jonathanturcotte** [comment]
The Jessie based prebuilds are not working on my Raspberry Pi 2 B. Script runs and completes almost instantly but no files of any type are copied over. 

I managed to get the 2015-05-27_CIRCLean.img working, though pdf conversion doesn't work. It creates an empty HTML file with no text for each pdf. 

Any help in getting the newer images to work would be greatly appreciated!

**Comment by Rafiot** [comment]
Can you try to add a sleep before the shutdown in rc.local, and tell me if you see any error message? This image works on my rpi2 B so it's weird... 

Are you 100% sure at the time you tested both keys were mountable? I had weird issues when once in a while the FS of one of the key gets broken and needs a fsck before I can use it again.

**Comment by jonathanturcotte** [comment]
Here is a photo of the output after adding a sleep to the end of rc.local

It looks as if the USB is being mounted read only?
![tmp_18497-img_20160623_0909431098640131](https://cloud.githubusercontent.com/assets/6924367/16304341/e9b3cb8a-3922-11e6-9c68-2fa5de33df93.jpg)

**Comment by Rafiot** [comment]
It fails at mounting both USB keys. Are they mountable on other file systems? Also, what is their file system?

**Comment by jonathanturcotte** [comment]
Source is FAT32 and destination is NTFS, and both mount under windows fine. I tested it on my linux VM and they mount on that as well.

**Comment by suryatkd** [comment]
Has there been any progress with the PDF files? Tested out several PDF files and none of them get transferred to the clean USB.  They're just labeled dangerous.

**Comment by Rafiot** [comment]
Well, if they have active content, they are labelled dangerous.

**Comment by suryatkd** [comment]
Ok makes sense.  The most recent build was supposed to boot into Raspbian if no USB keys were detected.  I get a log in/password prompt?

**Comment by dputtick** [comment]
It looks like the issues mentioned here are resolved. In the current release, NTFS keys mount as read-only. That will be fixed in the new release. Some of the other problems mentioned earlier are hard to replicate, but please open a new issue if you continue to have problems. Thanks!
