### ISSUE TITLE
Disable screen sleep

### ISSUE THREAD

**Issue by dputtick** [CIRCL/Circlean#44]
It's useful to be able to watch the progress of Circlean via an HDMI monitor if you have one. By default, the linux kernel will put the display to sleep after a period of no user input. The Circlean image should turn this feature off while booting. `setterm -powersave off -blank 0` should work.

**Comment by Rafiot** [comment]
Totally :) 

let's keep it open until we release a new image and add it in the init script.

**Comment by Rafiot** [comment]
Is it fixed btw? (I just wanted to add a link to the commit)

**Comment by Rafiot** [comment]
Can you just add it in the init script?

**Comment by dputtick** [comment]
@Rafiot Oops, just saw you messages. Moved it from rc.local to init.sh.

**Comment by Rafiot** [comment]
Thanks!
