### ISSUE TITLE
LED removed

### ISSUE THREAD

**Issue by Beercow** [CIRCL/Circlean#48]
Pull #46 removed the scripts for the LED and removed the entry from rc.local.

**Comment by Rafiot** [comment]
Yes, it wasn't used any more. Were you using it?

**Comment by Beercow** [comment]
I was. If no one else is using it, I acn just hang on to the script and add it after the fact.

**Comment by Rafiot** [comment]
Feel free to re-add it in a sub directory, that's not an issue.

**Comment by dputtick** [comment]
@Beercow sorry about that! Since it wasn't included in the official image we assumed it wasn't needed anymore. You're using led.c from /diode_controller, right? I'll add it back into the current repo and mention in the docs that you need extra hardware to use it.

**Comment by Beercow** [comment]
That would be the one. It's a good indicator of when everything is done without having to attach speakers or monitor. Nothing like a  bright LED looking back at you :)

**Comment by Beercow** [comment]
I also noticed there are releases missing in the repo that are mentioned on the main site. https://www.circl.lu/projects/CIRCLean/

Thanks again guys.

**Comment by dputtick** [comment]
Ah, thanks for noticing that, I'll add it to the changelog along with the new release.

**Comment by dputtick** [comment]
@Beercow Would also love feature requests, complaints, suggestions, etc etc if you have any

**Comment by GShaw18** [comment]
I Second the request for the led.c code to be restored to the project if not fully integrated to the pre-built image.  I'm working on a self contained Raspberry pi implementation for my company.   The pi will be secured in a small-ish project box and powered by a portable cellphone battery charger.     The status lights will negate the need for a small speaker or a display screen.

**Comment by GShaw18** [comment]
By the way, Thank you for your efforts.   This is a very interesting and useful project.

**Comment by dputtick** [comment]
@GShaw18 Thank you for using it! Please let us know how your implementation goes. The led files will be re-added in the PR that will come with the next release this week.
