### ISSUE TITLE
Release 2.1 missing

### ISSUE THREAD

**Issue by mboelen** [CIRCL/Circlean#57]
We reviewed this interesting project for our security tools section: https://linuxsecurity.expert/tools/circlean/

In the changelog (https://github.com/CIRCL/Circlean/blob/master/CHANGELOG.md), I see that version 2.1 is the latest. Yet the latest release (1.3) is a few years old.

**Comment by dputtick** [comment]
@mboelen Thanks! I think we stopped updating the release tags on Github. We have a new release coming soon, I'll make sure to add a tag.

**Comment by mboelen** [comment]
Sure, would appreciate a tag/release, so we can pick it up and promote it. Let us help you ;-)

**Comment by dputtick** [comment]
@mboelen Ok, we finally got the release 2.3 out and added a tag this time. Thanks for the suggestion and for spreading the word :)

**Comment by mboelen** [comment]
Perfect, it has been picked up on our side as well :)
