### ISSUE TITLE
Issue Getting CIRCLean to work

### ISSUE THREAD

**Issue by megan201296** [CIRCL/Circlean#60]
I was hoping someone might be able to help me out. I am trying to get this program to work. I am using the most recent pre-built image (using dd on mac to image the micro SD card). I have a Raspberry Pi 3 and two FAT32 USB drives. When I plug in the Raspberry Pi I have it connected to a monitor using HDMI and rather than actually running the program it just boots into Raspian. Any idea what I might be doing wrong?

**Comment by dputtick** [comment]
Hi @megan201296. Thanks for opening an issue. Our best guess is that this a regression involving the Pi 3 and Raspbian Stretch (this is the first image that has used Stretch and not Jessie). We're trying to figure out the specific problem at the moment.

**Comment by megan201296** [comment]
Thank you for the prompt response @dputtick ... Is there anything I can do to get it up and running in the meantime or do I need to just wait?

**Comment by dputtick** [comment]
@megan201296 We're trying to get a new release out ASAP. I'll post the fix here and update the Github repository as soon as we're sure what the problem is :). If you have access to the previous version, you could revert back to it. There might still be an active download link for the previous version, I'll double check about that.

**Comment by dputtick** [comment]
Ok @megan201296 (and anybody else), the temporary fix is as easy as deleting line 27 `/sbin/ifconfig eth0 down` in `/etc/rc.local`. We'll make a bug-fix release ASAP that includes this and also turns off the ethernet port by another mechanism (having it turned off is useful for preventing tampering with the Raspberry Pi, but is generally very unlikely to make the device less secure unless somebody physically gets their hands on it).

**Comment by megan201296** [comment]
I can wait for the pre-built image :)

**Comment by Rafiot** [comment]
@megan201296 here it is: https://www.circl.lu/assets/CIRCLean/2017-10-25_CIRCLean.img.gz
sha256: 99b2064f8e198897361762e80109449013a6e0c1b670b38ccb56ab58f99887e9

Please let me know if it works for you. I'll update the website as soon as possible.
