### ISSUE TITLE
Image not working on RasPi 3

### ISSUE THREAD

**Issue by secuninja** [CIRCL/Circlean#66]
First, thanks for that very interesting project 👍 
Unfortunately it seems not to run on RasPi 3 out of the box. 
While booting there are several Errors like 
- Failed to start Avahi mDNS/
- Failed to start LSB
- Failed to start Network Time Synchronization
- Failed to start Load/Save RF Kill Switch Status

Ending up in reboot or login prompt all of the time. 
Any ideas how to get it running?

**Comment by Rafiot** [comment]
There error can be ignored, they don't impact the device.

Did you plug both USB keys *before* booting the device?

**Comment by secuninja** [comment]
okay, now that I know that the errors are not the root cause of CIRCLEAN is not working I've tried several combinations of the source/destination USB and this combo is working for me:
![circlean_rpi3](https://user-images.githubusercontent.com/42541562/44341060-20a49f80-a487-11e8-97c4-579304583561.jpg)

**Comment by Rafiot** [comment]
Oo and that works? 

SRC and DST should be the other way around...
